version: '3.8'

services:
  app:
    build: .
    container_name: SkillSphere
    ports:
      - "3000:3000"  
    depends_on:
      - redis
    env_file: 
      - .env  
    environment:
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=redis://redis-server:6379  
      - PORT=3000
      - NODE_ENV=production
    command: ["node", "dist/index.js"]  
    restart: unless-stopped 

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped 
