version: '3.8'  

services:
  mongo:
    image: mongo:latest  
    container_name: mongo-db
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db  

  redis:
    image: redis:latest  
    container_name: redis-server
    ports:
      - "6379:6379"  

volumes:
  mongo_data: 
