const JWT_USER_PASSWORD = process.env.JWT_USER_PASSWORD || "maniTejaUser";
const JWT_ADMIN_PASSWORD = process.env.JWT_ADMIN_PASSWORD || "manitejaAdmin";
const RECEIVER_WALLET_ADDRESS = process.env.RECEIVER_WALLET_ADDRESS || "7gK5CPAaiJ6aEECZ1PKFxDa1cGn7wUSvqUeS7S8HbgnG"
const SOLANA_CONNECTION_URL = process.env.SOLANA_CONNECTION_URL || ""

export { JWT_ADMIN_PASSWORD, JWT_USER_PASSWORD , RECEIVER_WALLET_ADDRESS , SOLANA_CONNECTION_URL }; 
